name: Notify Telegram on Push (All Branches)

on:
  push:  # Semua push ke semua branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Send Telegram Message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          MESSAGE=$(git log -1 --pretty=format:'%s')
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="🚀 Push baru di *${BRANCH_NAME}* oleh *${AUTHOR}*:\n\n${MESSAGE}" \
            -d parse_mode="Markdown"
